spring:
  application:
    name: webportal-api
  profiles:
    active: ${ACTIVE_PROFILE:production}
  jpa:
    properties:
      ddl-auto: update
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: false
      enabled: true
      strategy:
        content:
          enabled: true
  datasource:
    url: jdbc:postgresql://cah8ha8ra8h8i7.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d4h8gjmol5r530
    username: uc82lnhg7241fu
    password: pc782a5384ededb1ad442142e19caf1016bdcbf44e98489892530b3e95efc9bba
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: sdaapp.email.sender@gmail.com
    password: "whdx yoez mmoz eatk"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    protocol: smtp
  mvc:
    throw-exception-if-no-handler-found: true
app:
  jwtSecret: "JWTSuperSecretKey"
  jwtRefreshTokenSecret: "JWTRefreshTokenSuperSecretKey"
  jwtExpirationInMs: 3600000
  jwtRefreshExpirationInMs: 3600000
  account:
    lock:
      time: 900000
  frontend:
    verifyemail:
      url: "http://localhost:4200/confirmemail"
    forgotpassword:
      url: "http://localhost:4200/resetpassword"
    base:
      url: "http://localhost:4200"
cors:
  allowed-origins: http://localhost:4200
  allowed-headers: Authorization,Content-Type
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

database:
  ssl-config:
  host: cah8ha8ra8h8i7.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com
  name: d4h8gjmol5r530
  port: 5432
  username: uc82lnhg7241fu
  password: pc782a5384ededb1ad442142e19caf1016bdcbf44e98489892530b3e95efc9bba

